import type { Metadata } from "next";
import type { ReactNode } from "react";
import localFont from "next/font/local";
import "./globals.css";
import Header from './components/header';
import Footer from './components/footer';

// Font configurations


// Metadata configuration
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout props interface
interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
}: Readonly<RootLayoutProps>) => {
  return (
    <html lang="en">
      <body
     
      >
        {children}
        <Header />
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;